security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_STAFF
     
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            
            # Use the full service ID reference
            access_denied_handler: 'App\Security\AccessDeniedHandler'
            
            logout:
                path: app_logout
                target: app_login_index

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/activity-logs, roles: ROLE_ADMIN }
        - { path: ^/reports, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/analytics, roles: ROLE_ADMIN}
        - { path: ^/home, roles: ROLE_ADMIN }
        - { path: ^/orders, roles: [ROLE_ADMIN, ROLE_STAFF] }
        - { path: ^/services, roles: [ROLE_ADMIN, ROLE_STAFF] }
        - { path: ^/settings, roles: [ROLE_ADMIN, ROLE_STAFF] }
        - { path: ^/, roles: ROLE_STAFF }